### ISSUE TITLE
Cannot redeclare composerRequired346c5441e2a9b0583ced00554218f59()

### ISSUE THREAD

**Issue by brightantwiboasiako** [spatie/phpunit-watcher#146]
Fatal error: Cannot redeclare composerRequired346c5441e2a9b0583ced00554218f59() (previously declared in .../vendor/composer/autoload_real.php:73) in .../vendor/composer/autoload_real.php on line 73

It appears this only happens in phpstorm and not vs-code. Running in a fresh install of Laravel 9 and running php 8.1.

**Comment by freekmurze** [comment]
I could not reproduce this.

**Comment by chuckienorton** [comment]
I am having the same issue. Laravel 9, php8.1, using global composer (composer installed via homebrew). I cannot install locally because of composer conflicts, else I would test to see if that's the issue. 

```

PHPUnit Watcher
===============

 PHPUnit Watcher 1.23.2 by Spatie and contributors.

 No config file detected. Using default options.

 Tests will be rerun when *.php files are modified in
 * /Users/me/Sites/budgeting.test/app
 * /Users/me/Sites/budgeting.test/tests


PHP Fatal error:  Cannot redeclare composerRequire3e7fafc018e7c294d21d64505a832b5a() (previously declared in /Users/me/sites/budgeting.test/vendor/composer/autoload_real.php:50) in /Users/me/Sites/budgeting.test/vendor/composer/autoload_real.php on line 50

Fatal error: Cannot redeclare composerRequire3e7fafc018e7c294d21d64505a832b5a() (previously declared in /Users/me/sites/budgeting.test/vendor/composer/autoload_real.php:50) in /Users/me/Sites/budgeting.test/vendor/composer/autoload_real.php on line 50
 
```

I think has popped up before, with same laravel/php specs [here](https://github.com/spatie/phpunit-watcher/issues/135) and [here](https://github.com/spatie/phpunit-watcher/issues/114). 

I love this package, by the way. And my code loves it too. ;-)
